version: "3.7"


# services:
#   docs:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: dev
#     ports:
#       - 8000:8000
#     volumes:
#       - ./:/app

services:
  restaurant_api:
    container_name: restaurant_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    environment:
      - NODE_ENV=development
